name: Compila y Genera PDF

on: 
  push:

jobs:
  compila:
    runs-on:ubuntu-latest

    steps:
    - name: tener copia local del repo
      uses: actions/checkout@v4.2.2
    - name: Instalar .NET en el runner
      uses: actions/setup-dotnet@v4
      with:
        # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx
        dotnet-version: "9.0.v"
    -name: Instalar dependencias
     run: dotnet restore
    -name: Compilar
     run: dotnet-build --no-restore
  crear-pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Markdown to PDF and HTML
      # You may pin to the exact commit or the version.
      # uses: BaileyJM02/markdown-to-pdf@1be26775add5f94fb55d4a2ce36ff7cad23b8dd0
      uses: BaileyJM02/markdown-to-pdf@v1
      with:
        # (Path) or (File) The location of the folder containing your .md or .markdown files, or a path to a single .md or .markdown file that you would like to convert.
        input_path: # optional
        # (Path) The location of the folder containing your .md or .markdown files
        input_dir: # optional
        # (Path) The location of the folder containing your images, this should be the route of all images
        images_dir: # optional
        # (String) The path you use to import your images that can be replaced with the server URL
        image_import: # optional
        # (Path) The location of the folder you want to place the built files
        output_dir: pdfs
        # (Boolean) Whether to also create a .html file
        build_html: true
        # (Boolean) Whether to create a .pdf file (the intended behaviour)
        build_pdf: # optional
        - name: Upload artifact
        # You may pin to the exact commit or the version.
        # uses: echapmanFromBunnings/upload-artifact@337a5a69b603f31f06936a711562a72b63b22151
        uses: echapmanFromBunnings/upload-artifact@v4
        with:
          # Artifact name
          name: docs
          # A file, directory or wildcard pattern that describes what to upload
          path: pdfs
        
